services:
  local-dir-rag:
    image: sualehfatehi/local-dir-rag:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${DOCS_DIRECTORY}:/data/docs
      - ${VECTOR_DB_PATH}:/data/vector_db
