name: Publish to TestPyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for OIDC authentication

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v5

      - id: setup-python
        name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - id: install-poetry
        name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          poetry --version

      - id: build-package
        name: Build package
        shell: bash
        run: |
          poetry build --verbose

      - id: publish-testpypi
        name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist/
          skip-existing: true
          verbose: true
