name: Docker Build and Publish

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: docker_login
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # This step extracts metadata for Docker tags from Git references
      - id: meta
        name: Extract metadata for Docker
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            # For Git tags (like v1.0.0), use the tag as Docker tag (1.0.0)
            type=semver,pattern={{version}}
            # Create additional tags for major.minor (e.g., 1.0)
            type=semver,pattern={{major}}.{{minor}}
            # Use Git tag as-is (including the 'v' prefix if present)
            type=ref,event=tag
            # Tag with the short SHA for all builds
            type=sha,format=short
            # Add 'latest' tag only for main branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - id: build_and_push
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
